<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Library</OutputType>
    <AssemblyName>ExoPlanets</AssemblyName>
    <Version>2.2.1.0</Version>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <DefaultItemExcludes Condition="$([System.Runtime.InteropServices.RuntimeInformation]::IsOSPlatform($([System.Runtime.InteropServices.OSPlatform]::Linux)))">$(DefaultItemExcludes);**/*.xaml.cs;**/*.xaml</DefaultItemExcludes>
  </PropertyGroup>
  <ItemGroup>
    <Service Include="{508349B6-6B84-4DF5-91F0-309BEEBAD82D}" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\NINA.Plugin\NINA.Plugin.csproj" />
    <ProjectReference Include="..\..\..\System.Windows.Compat\System.Windows.Compat.csproj" />
    <!-- Exclude System.Drawing.Common as it conflicts with our compat library -->
    <PackageReference Include="System.Drawing.Common" Version="*" ExcludeAssets="all" />
  </ItemGroup>
  <PropertyGroup />
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Properties\Settings.Designer.cs">
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <None Update="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="mkdir -p $HOME/.local/share/NINA/Plugins/3.0.0/ExoPlanets" />
    <Exec Command="cp $(TargetPath) $HOME/.local/share/NINA/Plugins/3.0.0/ExoPlanets/" />
    <Exec Command="cp $(MSBuildProjectDirectory)/resources/pandora*.csv $HOME/.local/share/NINA/Plugins/3.0.0/ExoPlanets/" />
  </Target>
</Project>
